import textblob
import subprocess
import tempfile
import os

def create_proselint_config():
    """Create a minimal Proselint configuration file."""
    config_content = """
    [checks]
    write-good.en.language-not-words = true
    """

    with tempfile.NamedTemporaryFile(mode='w+', delete=False) as temp_config:
        temp_config.write(config_content)
        return temp_config.name

def correct_grammar(text):
    """Corrects spelling errors and provides grammar and style suggestions."""

    try:
        # Spelling correction using TextBlob
        corrected_text = textblob.TextBlob(text).correct()

        # Create a Proselint configuration file
        config_file = create_proselint_config()

        # Grammar and style suggestions using Prose (using the command line tool)
        proselint_process = subprocess.Popen(["proselint", "--config", config_file], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        proselint_output, _ = proselint_process.communicate(input=str(corrected_text))
        
        # Remove the temporary Proselint configuration file
        os.remove(config_file)

        # Return the corrected text and suggestions (if any)
        return corrected_text
    except Exception as e:
        # Handle exceptions (e.g., TextBlob or Proselint errors)
        print(f"An error occurred: {e}")
        return text

if __name__ == "__main__":
    # Example usage
    text = """
    MY NAME'S CARMAN MI AM MY BROTHER'S AN ATIC MY MY BROTHER WASN'T AT IT AND THIS MORNING I AM SIRRY I I FORGOT IM BUT BEFORE I CAME TO ALLAN ON I WAS COOK I MEAN I M STILL A COOK I'M JUST A DIFFERENT KIND OF COOK I GUESS MY BROTHER AND I WE WOULD COOK A LOT TOGETHER ESPECIALLY WHEN WE WERE KIDS ALL THAT'S THATS WHEN WE WERE CLOSEST FOOD WAS ALWAYS OUR COMMON GROUND WE WANTED TO OPEN A RESTAURANT TOGETHER I WE HAD A NAME WE HAD A VIYE ALL OF IT MY BROTHER COULD MAKE YOU FEEL CONFIDENT IN YOURSELF OU LIKE ONE I WAS A KID IF I WAS NERVOUS I WAS SCARED I WOULDN' WANT TO DO SOMETHING HE'D ALWAYS TELL ME TO JUST FACE IT YOUON'T GET IT OVER WITH HE WOULD ALWAYS SAY IM STUPID HE WOULD ALWAYS SAY AM LET IT RIT HE WAS LOUD AND HE WAS HOLARIOUS AND HE HAD THIS AMAZING ABILITY HE COULD JUST TAKE A WALK INTO A ROOM AND HE COULD TAKE THE TEMPERATURE OF IT INSTANTLY YOU KNOW HE COULD JUT TEAKE A DILINAND OM I'M NOT BUILT LIKE THAT AN I AM I NEVER LOT OF FRIENDS GROWIN OUT I HAD AA STUTTER WHEN I WAS A KID I WAS SCARED TO SPEAK HALF THE TIME AND I OT SHEDY GRADES E I COULDN'T PAY ATTENTION IN SCHOOL I DIDN'T GET INTO COLLEGE AND HAVETING GIRL FRIENDS ON ON'L THNK OM FUNNY I ALWAYS THOUGHT MY BROTHER WAS MY BEST FRIEND LIKE LIKE WEJUST KNEW EVERYTHING ABOUT EACH OTHER EXCEPT EVERYBODY THOUGHT HE WAS THERE BEST FRIEND YOU KNOW HE WAS THAT HE WAS THAT MAGNETIC AND IM I DIDN'T KNOW MY BROTHER WAS USING DRUG WHAT IS THAT SAY AS WE GOT OLDER I REALIZED I DIDN'T KNOW ANYTHING ABOUT HIM REALLY HE STOPPED LED IM INTO THE RESTAURANT A COUPLE YEARS AGO HE JUST COT ME OFF COLD AND AT IM THAT HURT YOU KNOW AND I THINK THAT JUST AFFLICK THIS SWITCHIN ME WHERE I WAS LIKE OKEH FUCK YOU WATCH THIS AND BECAUSE WE HAD THIST CONNECTION THROUGH FOOD AND HE'D MADE ME FEEL SO RIJECTED AND LAME AND SHIDDY AND UNCOOL I MADE THIS PLAIN WHERE I WAS GO TOCAL WORK AN ALL THE BESTAURESTAURANTS IN THE WORLD YOU KNALL LIKE LIKE OMINABLE WORKIN REAL KITCHENS LIKE FUNKMAMMIN DAD'S PIECE OF SHIP RIGHT AND IT SOUNDS RIDICULOUS YOU KNON ME SAYING THAT NOW BUT THAT'S THAT'S THAT'S WHAT I DID AND I GOT THE SHIC KICKED AT OF ME AND I SEPARATED HERBS AND I SHOCKED OYSTERS AND CLAMS AND UNEY AND I CUT MYSELF AND I GOT GARLIC AND ONIONS AND PEPPERS AND MY FINGER NAILS AND IN MY EVES AND MY SKIN WAS DRY AND OILY AT THE SAME TIME I HAD CALISES ON MY FINGERS FROM THE KNIVES AND MY STOMACH WAS FUCKED AND IT WAS EVERYTHING AND A COUPLE YEARS LATER THIS FUNNY THING HAPPENED WHICH IS LIKE FOR THE FIRST TIME IN MY LIFE I I STARTED TO FIND THIS A TI STATION FOR MYSELF AND I WAS FAST I WASN'T AFRAID AND IT WAS CLEAR AND I I FELT I FELT HOQUET YOU KNOW I KNEW WHICH VEGETABLES WENT TOGETHER PROTEIN'S TEMPERATURE SAUCES ALL THAT SHINT WHEN SOMEBODY KNEW CAME INTO THE RESTAURANT TO STAGE I'D LOOK AT THEM LIKE THEY WERE COMPETITION LIKE OMINOUS SMOKE THIS MOTHER FUCKER I FELT LIKE I COULD SPEAK THROUGH THE FOOD LIKE I COULD COMMUNICATE THROUGH CREATIVITY AND THAT KIND OF CONFIDENT YOU KNOW LIKE I WAS FINALLY I WAS I WAS GOOD AT SOMETHING THAT WAS SO NEW AND THI WAS SO EXCITING AND I JUT WANTED HIM TO KNOW THAT AND FUCK I JUST WANTED HIM TO BE LIKE GOOD JOB AND THE MORE HE WOULDN'T RESPOND AND THE MORE OUR RELATIONSHIP CONNISTRAINED THE DEEPER INTO THIS I WENT AND THE BETTER I GOT AND THE MORE PEOPLE I CUT OUT THE QUIET OF MY LIFE GOT AND THE ROUTINE OF THE KITCHEN WAS SO CONSISTENT AND EXACTINT AND BUSY AND HARD AND ALIVE AND I LOST TRACK OF TIME AND HE DIED AND HE LEFT ME AS RESTAURANT AND OVER THE LAST COUPLE MONTHS I'VE BEEN TRYING TO FIX IT BECAUSE IT WAS IN ROUGH SHAPE AND I THINK IT'S VERY CLEAR THAT ME TRYING TO FIX THE RESTAURANT IT WAS ME TRYING TO FIX WHATEVER WAS HAPPENING WITH MY BROTHER AN OTTOO MAY BE FIX THE WHOLE FAMILY BECAUSE THAT RESTAURANT IT HAS AND IT DOES MEAN A LOT TOF PEOPLE IT MEANS A LOT TO ME I JUST DON'T KNOW IF ITEVER MEANT ANYTHING TO IM
    """
    corrected_text = correct_grammar(text)

    print("Corrected text:", corrected_text)  # Output: This is a sentence with spelling errors and grammar issues.
